# Generated by Django 4.0.6 on 2022-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=400)),
                ('address2', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
